### ISSUE TITLE
Homework review

### ISSUE THREAD

**Issue by adadychanka** [KyzAlexander/HomeWorkReact15.02.22#1]
https://github.com/KyzAlexander/HomeWorkReact15.02.22/blob/1fc9edd5283cde7c15ecd70fd02f080c06c38d11/index.js#L2

Для названия компонента в основном используется существительное.

Всё остальное хорошо, то что я и ожидал увидеть!

**Comment by KyzAlexander** [comment]
Понял, спасибо. Буду знать на будущее
